"""Split combined prefetcher+replacement source on OpenEvolve markers."""

from __future__ import annotations

import re
from typing import Tuple

PREFETCHER_BEGIN = "// === OPENEVOLVE_PREFETCHER_BEGIN ==="
PREFETCHER_END = "// === OPENEVOLVE_PREFETCHER_END ==="
REPLACEMENT_BEGIN = "// === OPENEVOLVE_REPLACEMENT_BEGIN ==="
REPLACEMENT_END = "// === OPENEVOLVE_REPLACEMENT_END ==="

_BLOCK_RE = re.compile(
    r"^[ \t]*//[ \t]*===[ \t]*OPENEVOLVE_(PREFETCHER|REPLACEMENT)_(BEGIN|END)[ \t]*===[ \t]*$",
    re.MULTILINE,
)

MARKER_KEYS = ("PREFETCHER_BEGIN", "PREFETCHER_END", "REPLACEMENT_BEGIN", "REPLACEMENT_END")


def parse_marker_positions(text: str) -> dict[str, int]:
    """Return byte offsets for each required whole-line split marker."""

    markers: dict[str, int] = {}
    for match in _BLOCK_RE.finditer(text):
        key = f"{match.group(1)}_{match.group(2)}"
        if key in markers:
            raise ValueError(f"Duplicate split marker: {key}")
        markers[key] = match.start()

    missing = set(MARKER_KEYS) - markers.keys()
    if missing:
        raise ValueError(
            "Combined source is missing required split markers: " + ", ".join(sorted(missing))
        )

    if not (markers["PREFETCHER_BEGIN"] < markers["PREFETCHER_END"]):
        raise ValueError("Prefetcher BEGIN marker must precede END marker")
    if not (markers["REPLACEMENT_BEGIN"] < markers["REPLACEMENT_END"]):
        raise ValueError("Replacement BEGIN marker must precede END marker")
    if not (markers["PREFETCHER_END"] < markers["REPLACEMENT_BEGIN"]):
        raise ValueError(
            "Prefetcher block must appear before the replacement block in the combined source"
        )
    return markers


def split_combined_source(text: str) -> Tuple[str, str]:
    """Split a combined source blob into (prefetcher_source, replacement_source)."""

    markers = parse_marker_positions(text)

    def _slice(begin_key: str, end_key: str, header: str) -> str:
        begin_idx = text.find("\n", markers[begin_key])
        if begin_idx == -1:
            raise ValueError(f"Marker {begin_key} is not followed by a newline")
        body = text[begin_idx + 1 : markers[end_key]]
        return header + body

    pf_header = (
        "// AUTO-GENERATED by workflows/combined/evaluator.py from the combined initial_program.cc.\n"
        "// Hand edits will be overwritten on the next evolution iteration.\n\n"
    )
    rp_header = (
        "// AUTO-GENERATED by workflows/combined/evaluator.py from the combined initial_program.cc.\n"
        "// Hand edits will be overwritten on the next evolution iteration.\n\n"
    )

    pf_source = _slice("PREFETCHER_BEGIN", "PREFETCHER_END", pf_header).rstrip() + "\n"
    rp_source = _slice("REPLACEMENT_BEGIN", "REPLACEMENT_END", rp_header).rstrip() + "\n"
    return pf_source, rp_source
