// AUTO-GENERATED by workflows/combined/evaluator.py from the combined initial_program.cc.
// Hand edits will be overwritten on the next evolution iteration.

// Baseline: DRRIP (Dynamic RRIP), aligned with ChampSim replacement/drrip.
// Evolve toward coordinated prefetcher/replacement behaviour; keep API compatible
// with openevolve_replacement.h (do not change the header).

#include <algorithm>
#include <cassert>
#include <cstdint>
#include <vector>

#include "msl/fwcounter.h"
#include "openevolve_replacement.h"

// EVOLVE-BLOCK-START
namespace {

constexpr unsigned maxRRPV = 3;
constexpr unsigned BRRIP_MAX = 32;
constexpr std::size_t PSEL_WIDTH = 10;

enum class drrip_set_kind { follower, brrip_leader, srrip_leader };

struct openevolve_replacement_state {
  long num_way = 0;
  unsigned brrip_counter = 0;
  std::vector<champsim::msl::fwcounter<PSEL_WIDTH>> PSEL;
  std::vector<unsigned> rrpv;
};

openevolve_replacement_state oer_state{};

unsigned& access_rrpv(long set, long way)
{
  return oer_state.rrpv.at(static_cast<std::size_t>(set * oer_state.num_way + way));
}

void update_brrip(long set, long way)
{
  access_rrpv(set, way) = maxRRPV;
  oer_state.brrip_counter++;
  if (oer_state.brrip_counter == BRRIP_MAX) {
    oer_state.brrip_counter = 0;
    access_rrpv(set, way) = maxRRPV - 1;
  }
}

void update_srrip(long set, long way) { access_rrpv(set, way) = maxRRPV - 1; }

drrip_set_kind set_kind(long set, openevolve_replacement* self)
{
  switch (self->get_set_sample_category(set)) {
    case 0:
      return drrip_set_kind::brrip_leader;
    case 1:
      return drrip_set_kind::srrip_leader;
    default:
      return drrip_set_kind::follower;
  }
}

} // namespace

openevolve_replacement::openevolve_replacement(CACHE* cache) : openevolve_replacement(cache, cache->NUM_SET, cache->NUM_WAY) {}

openevolve_replacement::openevolve_replacement(CACHE* cache, long sets, long ways) : replacement(cache)
{
  oer_state.num_way = ways;
  oer_state.brrip_counter = 0;
  oer_state.rrpv.assign(static_cast<std::size_t>(sets * ways), 0);
  oer_state.PSEL.clear();
  oer_state.PSEL.reserve(NUM_CPUS);
  const auto psel_mid = static_cast<long long>(1) << (PSEL_WIDTH - 1);
  for (std::size_t i = 0; i < NUM_CPUS; ++i) {
    oer_state.PSEL.emplace_back(psel_mid);
  }
}

long openevolve_replacement::find_victim(uint32_t triggering_cpu, uint64_t instr_id, long set, const champsim::cache_block* current_set,
                                         champsim::address ip, champsim::address full_addr, access_type type)
{
  (void)triggering_cpu;
  (void)instr_id;
  (void)current_set;
  (void)ip;
  (void)full_addr;
  (void)type;

  auto begin = std::next(std::begin(oer_state.rrpv), set * oer_state.num_way);
  auto end = std::next(begin, oer_state.num_way);
  auto victim = std::max_element(begin, end);
  if (const unsigned rrpv_update = maxRRPV - *victim; rrpv_update != 0) {
    for (auto it = begin; it != end; ++it) {
      *it += rrpv_update;
    }
  }
  assert(begin <= victim);
  assert(victim < end);
  return std::distance(begin, victim);
}

void openevolve_replacement::replacement_cache_fill(uint32_t triggering_cpu, long set, long way, champsim::address full_addr, champsim::address ip,
                                                    champsim::address victim_addr, access_type type)
{
  (void)full_addr;
  (void)ip;
  (void)victim_addr;

  if (access_type{type} == access_type::WRITE) {
    access_rrpv(set, way) = maxRRPV - 1;
    return;
  }

  auto& selector = oer_state.PSEL.at(triggering_cpu);
  switch (set_kind(set, this)) {
    case drrip_set_kind::follower:
      if (selector.value() > (selector.maximum / 2)) {
        update_brrip(set, way);
      } else {
        update_srrip(set, way);
      }
      break;
    case drrip_set_kind::brrip_leader:
      oer_state.PSEL[triggering_cpu]--;
      update_brrip(set, way);
      break;
    case drrip_set_kind::srrip_leader:
      oer_state.PSEL[triggering_cpu]++;
      update_srrip(set, way);
      break;
  }
}

void openevolve_replacement::update_replacement_state(uint32_t triggering_cpu, long set, long way, champsim::address full_addr, champsim::address ip,
                                                      champsim::address victim_addr, access_type type, uint8_t hit)
{
  (void)triggering_cpu;
  (void)full_addr;
  (void)ip;
  (void)victim_addr;

  if (hit) {
    if (access_type{type} == access_type::WRITE) {
      access_rrpv(set, way) = maxRRPV - 1;
      return;
    }
    access_rrpv(set, way) = 0;
  }
}
// EVOLVE-BLOCK-END
